---
title: R for justice transparency
author: Ryan Gentzler
date: '2019-12-15'
slug: r-for-justice-transparency
categories: []
tags: []
description: ''
externalLink: ''
series: []
---

I'm Ryan Gentzler, Director of [Open Justice Oklahoma](http://www.openjusticeok.org) at the [Oklahoma Policy Institute](http://www.okpolicy.org).

Over the past three years, I've developed tools almost exclusively in R to scrape, analyze, visualize, and communicate data generated by Oklahoma's justice system. As a state with one of the highest incarceration rates in the country, the need for a more transparent and accountable justice system could not be greater. Oklahoma also happens to have one of the most easily accessible and comprehensive court websites in the country, providing a unique opportunity to measure our justice system in real time.

This, my personal website, will provide a tour of the tools we use, with an initial emphasis on the development of the `ojo` R package. My hope is that others with interests in courts, the justice system, and policy in general will find something useful here.